### ISSUE TITLE
VEML6075 and nerves

### ISSUE THREAD

**Issue by alpa669** [akoutmos/nerves_weather_station#2]
Hi,
Can I use the veml7700 library to interface with a veml6075 in nerves/elixir?

Thanks !!

**Comment by fhunleth** [comment]
Hi @alpa669,

I have not used the [VEML7700 library](https://github.com/elixir-sensors/veml7700), but I know that the author of that library is very helpful. If it doesn't work, it might just be a minor change to support. Could you try posting an issue to his library so he can respond? Perhaps also try it and share what happens when you do.

Good luck!

**Comment by alpa669** [comment]
Thanks @fhunleth,
i will try to search differences from two datasheets.
